name: ci

on: [push]

jobs:
    compile:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Set up node
              uses: actions/setup-node@v3

            - name: Compile
              run: npm ci && npm run build

    publish:
        needs: [compile]
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Set up node
              uses: actions/setup-node@v3

            - name: Build
              run: npm ci && npm run build

            - name: Publish to npm
              run: |
                  npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
                  npm publish --access public
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
